DROP TABLE IF EXISTS class_enrollments CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS discipline_lessons CASCADE;
DROP TABLE IF EXISTS lesson_learning_objects CASCADE;
DROP TABLE IF EXISTS lessons CASCADE;
DROP TABLE IF EXISTS disciplines CASCADE;
